# RPM package for ModulationWaveform
# This file is regularly AUTO-GENERATED by the IDE. DO NOT MODIFY.

# By default, the RPM will install to the standard REDHAWK SDR root location (/var/redhawk/sdr)
# You can override this at install time using --prefix /new/sdr/root when invoking rpm (preferred method, if you must)
%{!?_sdrroot: %define _sdrroot /var/redhawk/sdr}
%define _prefix %{_sdrroot}
Prefix: %{_prefix}

Name: ModulationWaveform
Summary: Waveform ModulationWaveform
Version: 1.0.0
Release: 1
License: None
Group: REDHAWK/Waveforms
Source: %{name}-%{version}.tar.gz
# Require the controller whose SPD is referenced
Requires: ModulationAssemblyController
# Require each referenced component
Requires: PSKBasebandMod UpZero fastfilter RealPart ModulationAssemblyController FreqShift
BuildArch: noarch
BuildRoot: %{_tmppath}/%{name}-%{version}

%description
Waveform demonstrating a PSK Modulation diagram.
Will upsample and filter off the and shift the baseband signal up to a desired frequency. The assembly controller should be used to change values.

%prep
%setup

%install
%__rm -rf $RPM_BUILD_ROOT
%__mkdir_p "$RPM_BUILD_ROOT%{_prefix}/dom/waveforms/%{name}"
%__install -m 644 ModulationWaveform.sad.xml $RPM_BUILD_ROOT%{_prefix}/dom/waveforms/%{name}/ModulationWaveform.sad.xml

%files
%defattr(-,redhawk,redhawk)
%dir %{_prefix}/dom/waveforms/%{name}
%{_prefix}/dom/waveforms/%{name}/ModulationWaveform.sad.xml
